version: '2'
services:
    adap_workflow-app:
        image: adap_workflow
        external_links:
            - adap_workflow-postgresql:postgresql
            - adap_workflow-elasticsearch:elasticsearch
            - jhipster-registry:registry
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_CLOUD_CONFIG_URI=http://admin:admin@registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/adap_workflow
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
    adap_workflow-postgresql:
        extends:
            file: postgresql.yml
            service: adap_workflow-postgresql
    adap_workflow-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: adap_workflow-elasticsearch
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
