version: '2'
services:
    adap_workflow-postgresql:
        container_name: adap_workflow-postgresql
        image: postgres:9.5.1
        # volumes:
        #     - ~/volumes/jhipster/adap_workflow/postgresql/:/var/lib/postgresql/
        environment:
            - POSTGRES_USER=adap_workflow
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
