package com.innvo
import com.innvo.AssetModel;
import com.innvo.LocationModel;
import org.json.JSONObject;
import java.util.List;
import java.util.ArrayList;
import com.innvo.ScoreModel;
global com.innvo.SaveScore scoreVal;
global List<ScoreModel> scoreList;
import java.util.Set;
import com.innvo.domain.Status;
rule "One"
ruleflow-group "Group2"

    when
       assetModel : AssetModel($locations : locations)
       locationModel : LocationModel() from $locations  
       ruleFile : String()
       eval(locationModel.getStatecode().contains("MD") && !ruleFile.contains("localhost:8099"))
    then
        System.out.println("Asset Model with location Values :" +assetModel);
        System.out.println("Location Model Values :" +locationModel);
        System.out.println("Rule file name :" +ruleFile);
        ScoreModel score = new ScoreModel();
        JSONObject details = new JSONObject();
		details.put("ScenarioName", "Scenario_One");
		details.put("ScoreCategoryName", "Category_One");
		details.put("ScoreTypeName", "Category_One");
		details.put("Value", 101);
		details.put("RuleName", drools.getRule().getName());
	    score.setDetails(details.toString());
		score.setStatus(Status.Active);
		score.setValue(10d);
		score.setRulename("Rule_one");
		score.setRulefilename(ruleFile);
		score.setDomain("DEMO");
        System.out.println("Score :" +score);
        scoreVal.addScore(score);
end
