package com.innvo
import com.innvo.AssetModel;
import java.util.List;
import java.util.ArrayList;
import com.innvo.ScoreModel;
global com.innvo.SaveScore scoreVal;
import java.time.ZonedDateTime;
import java.time.ZoneId;
rule "One" salience 5
ruleflow-group "Group1"

    when
       statecodesVal : AssetModel($stateCodesValues : stateCodesValues)
       value : String() from $stateCodesValues
       assetId:Long()
       eval(statecodesVal.getStateCodesValues().contains("MD") || assetId % 2==0 || assetId % 2!=0 )
    then
        System.out.println("Enter the rule one :" +value);
        System.out.println("Enter the rule one :" +assetId);
        System.out.println("Enter the rule one :" +statecodesVal.getId());
        AssetModel assetStatecodeValues =new AssetModel();
		assetStatecodeValues.setId(statecodesVal.getId());
        ScoreModel score= new ScoreModel();
        score.setStatus("Active");
        score.setRecordtype("TEST");
        score.setLastmodifiedby("TEST");
        score.setLastmodifieddatetime("2016-06-27T07:46:34.570Z");
        score.setValue(10l);
        score.setDomain("DEMO");
        score.setAsset(assetStatecodeValues);
        System.out.println("Score :" +score);
        scoreVal = new SaveScore(score);   

end
